### ISSUE TITLE
installation steps

### ISSUE THREAD

**Issue by AnushaY1** [narmitech/cloudwatchmetricbeat#2]
can you please installation steps.. clearly...

i am getting below error..
 path :- /tmp/cloudwatchmetricbeat/beater
             => go build
            # _/tmp/cloudwatchmetricbeat/beater
Error:-
./cloudwatchmetricbeat.go:25:9: undefined: publisher.Client

**Comment by AnushaY1** [comment]
can we use this metric in production ???

**Comment by phillbaker** [comment]
Hello! The readme shows [how to clone the repo and use `make` to build the project](https://github.com/narmitech/cloudwatchmetricbeat#build). 

As well, there's a dockerfile in the repo - that's probably the easiest way to use the binary. We'll add a binary output to the travis build for releases and document the docker file in the readme.

We do use this in production 😀 .
