### ISSUE TITLE
instillation steps still failing.

### ISSUE THREAD

**Issue by jasonlang80** [narmitech/cloudwatchmetricbeat#4]
I think the code has a bug:
$:~/go/src/github.com/narmitech/cloudwatchmetricbeat$ pwd
/home/jasonlang/go/src/github.com/narmitech/cloudwatchmetricbeat
$:~/go/src/github.com/narmitech/cloudwatchmetricbeat$ make
go build -i -ldflags "-X github.com/elastic/beats/libbeat/version.buildTime=2018-06-20T17:26:32Z -X github.com/elastic/beats/libbeat/version.commit=fbf0b84fb01fd271b26122dee758166b20e226ca"
# github.com/narmitech/cloudwatchmetricbeat/beater
beater/cloudwatchmetricbeat.go:25:9: undefined: publisher.Client
vendor/github.com/elastic/beats/libbeat/scripts/Makefile:112: recipe for target 'cloudwatchmetricbeat' failed
make: *** [cloudwatchmetricbeat] Error 2

**Comment by jasonlang80** [comment]
I think this is an issue with the library used for client having changed recently. still digging into it.

**Comment by jasonlang80** [comment]
Found the issue. Your instructions do not include the "make collect" step. I found that in your Dockerfile.

**Comment by phillbaker** [comment]
Sorry about that @jasonlang80 can you do a PR to the readme?

**Comment by jasonlang80** [comment]
done.
